#spring.application.name=brchain
#
#server.port = 8080
#
#
#spring.servlet.multipart.maxFileSize=99MB
#spring.servlet.multipart.maxRequestSize=99MB
#
#spring.datasource.username=brchain
#spring.datasource.password=nhepropass
#spring.datasource.url=jdbc:mysql://192.168.65.169:3306/brchain?serverTimezone=UTC
#
#
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#
#spring.main.allow-bean-definition-overriding: true
#
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.initialization-mode=always
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true;
#spring.profiles.active=local
#
#brchain.ip=192.168.65.169
#brchain.ssh.port=22
#brchain.ssh.user=root
#brchain.ssh.pass=1111
##brchain.sourcedir=/svc/nhblock/brchain
#brchain.sourcedir=/svc/nhblock/prod_brchain
#brchain.logdir=/svc/nhblock/logs
#brchain.datadir=/svc/nhblock/data
#brchain.networkmode=brchain-network

brchain:
    datadir: /svc/nhblock/data
    ip: 192.168.65.169
    logdir: /svc/nhblock/logs
    networkmode: brchain-network
    sourcedir: /svc/nhblock/prod_brchain
    ssh:
        pass: 1111
        port: 22
        user: root
server:
    port: 8080
spring:
    application:
        name: brchain
    datasource:
        initialization-mode: always
        password: nhepropass
        url: jdbc:mysql://192.168.65.169:3306/brchain?serverTimezone=UTC
        username: brchain
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true;
        show-sql: true
    main:
        allow-bean-definition-overriding: true
    profiles:
        active: local
    servlet:
        multipart:
            maxFileSize: 99MB
            maxRequestSize: 99MB
